MODEL_2D:
  TYPE: "SalsaNextSeg"
  DUAL_HEAD: True
MODEL_3D:
  TYPE: "PVD"
  DUAL_HEAD: True
DATASET_SOURCE:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_usa",)
  NuScenesSCN:
    root_dir: "/data/datasets/nuScenes/nuscenes_preprocess_lidar/preprocess"
DATASET_TARGET:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_singapore",)
  VAL: ("val_singapore",)
  TEST: ("test_singapore",)
  NuScenesSCN:
    root_dir: "/data/datasets/nuScenes/nuscenes_preprocess_lidar/preprocess"
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
OPTIMIZER_DIS:
  TYPE: "Adam"
  BASE_LR: 0.0001
  Adam:
      betas: (0.9, 0.99)
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
SCHEDULER_DIS:
  TYPE: "PolyLR"
  PolyLR:
      power: 0.9
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [2.42607725, 4.61879653, 5.72875704, 3.69461499, 1.]
  LION_XA:
    lambda_xm_src: 0.8
    lambda_xm_trg: 0.1
    lambda_pixels: 0.8
    lambda_G_trg_2d_pred: 0.07
    lambda_G_trg_3d_pred: 0.05
    lambda_G_trg_2d_feat: 0.07
    lambda_D_src_2d_pred: 0.1
    lambda_D_src_3d_pred: 0.1
    lambda_D_src_2d_feat: 0.1
    lambda_D_trg_2d_pred: 0.2
    lambda_D_trg_3d_pred: 0.2
    lambda_D_trg_2d_feat: 0.2
VAL:
  BATCH_SIZE: 8
  PERIOD: 5000
OUTPUT_DIR: "/workspace/lion-xa/LION_XA/output/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/lion_xa