#                1           2           3           4 
transformation: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
adaption: 'cp'
number_of_scans: 1
preserve_float: True
voxel_size: 0.05
batch_interval: 1
#              xmin xmax ymin ymax zmin zmax
voxel_bounds: [ -50,  50, -50,  50,  -5,   5]
ignore: [0]
moving: []
labels: 
  0: "unlabeled"
  4: "1 person"
  5: "2+ person"
  6: "rider"
  7: "car"
  8: "trunk"
  9: "plants"
  10: "traffic sign 1" # standing sign
  11: "traffic sign 2" # hanging sign
  12: "traffic sign 3" # high/big hanging sign
  13: "pole"
  14: "trashcan"
  15: "building"
  16: "cone/stone"
  17: "fence"
  21: "bike"
  22: "ground" # class definition
color_map: # bgr
  0: [0, 0, 0] # 0: "unlabeled"
  4: [30, 30, 255] # 4: "1 person"
  5: [30, 30, 255] # 5: "2+ person"
  6: [200, 40, 255] # 6: "rider"
  7: [245, 150, 100] # 7: "car"
  8: [0, 60, 135] # 8: "trunk"
  9: [0, 175, 0] # 9: "plants"
  10: [255, 0, 0] # 10: "traffic sign 1"
  11: [255, 0, 0] # 11: "traffic sign 2"
  12: [255, 0, 0] # 12: "traffic sign 3"
  13: [255, 240, 150] # 13: "pole"
  14: [125, 255, 0] # 14: "trashcan"
  15: [0, 200, 255] # 15: "building"
  16: [50, 255, 255] # 16: "cone/stone"
  17: [50, 120, 255] # 17: "fence"
  21: [100, 230, 245] # 21: "bike"
  22: [255, 0, 255] # 22: "ground"
