MODEL_2D:
  TYPE: "SalsaNextSeg"
  DUAL_HEAD: True
  NUM_CLASSES: 6
MODEL_3D:
  TYPE: "SCN"
  DUAL_HEAD: True
  NUM_CLASSES: 6
DATASET_SOURCE:
  TYPE: "SemanticKITTISCN"
  TRAIN: ("train",)
  SemanticKITTISCN:
    root_dir: "/_data/datasets/SemanticKITTI"
    trgl_dir: "/_data/datasets/SemanticKITTI/semantic_kitti2nuscenes"
    nuscenes: True
DATASET_TARGET:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_all",)
  VAL: ("val_all",)
  TEST: ("test_all",)
  NuScenesSCN:
    root_dir: "/_data/datasets/nuScenes/data/nuscenes"
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER_2D:
  TYPE: "SGD"
  BASE_LR: 0.0025
OPTIMIZER_3D:
  TYPE: "Adam"
  BASE_LR: 0.001
OPTIMIZER_DIS:
  TYPE: "Adam"
  BASE_LR: 0.0001
  Adam:
      betas: (0.9, 0.99)
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
SCHEDULER_DIS:
  TYPE: "PolyLR"
  PolyLR:
      power: 0.9
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [1.66759149, 1.09394955, 1.23188501, 1.09613089, 1.43978661, 1.]
  LION_XA:
    lambda_xm_src: 0.1
    lambda_xm_tgl: 0.02
    lambda_xm_trg: 0.01
    lambda_pixels: 0.1
    lambda_G_trg_2d_pred: 0.07
    lambda_G_trg_3d_pred: 0.05
    lambda_G_trg_2d_feat: 0.001
    lambda_D_src_2d_pred: 0.1
    lambda_D_src_3d_pred: 0.1
    lambda_D_src_2d_feat: 0.1
    lambda_D_trg_2d_pred: 0.2
    lambda_D_trg_3d_pred: 0.2
    lambda_D_trg_2d_feat: 0.2
VAL:
  BATCH_SIZE: 6
  PERIOD: 5000
OUTPUT_DIR: "/workspace/lion-xa/LION_XA/output/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/lion_xa