MODEL_2D:
  TYPE: "SalsaNextSeg"
  DUAL_HEAD: True
  NUM_CLASSES: 6
MODEL_3D:
  TYPE: "PVD"
  DUAL_HEAD: True
  NUM_CLASSES: 6
DATASET_SOURCE:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_all",)
  NuScenesSCN:
    root_dir: "/_data/datasets/nuScenes/data/nuscenes"
DATASET_TARGET:
  TYPE: "SemanticKITTISCN"
  TRAIN: ("train",)
  VAL: ("val",)
  TEST: ("test",)
  SemanticKITTISCN:
    root_dir: "/_data/datasets/SemanticKITTI"
    nuscenes: True
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
OPTIMIZER_DIS:
  TYPE: "Adam"
  BASE_LR: 0.0001
  Adam:
      betas: (0.9, 0.99)
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
SCHEDULER_DIS:
  TYPE: "PolyLR"
  PolyLR:
      power: 0.9
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [1.60485736, 1., 1.58943799, 1.22508361, 1.59556247, 1.37158822]
  LION_XA:
    lambda_xm_src: 0.1
    lambda_xm_trg: 0.01
    lambda_pixels: 0.1
    lambda_G_trg_2d_pred: 0.07
    lambda_G_trg_3d_pred: 0.07
    lambda_G_trg_2d_feat: 0.07
    lambda_D_src_2d_pred: 0.1
    lambda_D_src_3d_pred: 0.1
    lambda_D_src_2d_feat: 0.1
    lambda_D_trg_2d_pred: 0.15
    lambda_D_trg_3d_pred: 0.15
    lambda_D_trg_2d_feat: 0.15
VAL:
  BATCH_SIZE: 8
  PERIOD: 5000
OUTPUT_DIR: "/workspace/lion-xa/LION_XA/output/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/lion_xa